STYLE_TOPLEFT=" "
STYLE_TOPRIGHT=" "
STYLE_TOPMIDDLE=" "
STYLE_BOTTOMLEFT=" "
STYLE_BOTTOMRIGHT=" "
STYLE_BOTTOMMIDDLE=" "
STYLE_SIDECOL=" "
STYLE_TITLEHOLESTART=" "
STYLE_TITLEHOLEEND=" "
STYLE_SELECTED=" "

style::double() {
  STYLE_TOPLEFT="\u2554"
  STYLE_TOPRIGHT="\u2557"
  STYLE_TOPMIDDLE="\u2550"
  STYLE_BOTTOMLEFT="\u255A"
  STYLE_BOTTOMRIGHT="\u255D"
  STYLE_BOTTOMMIDDLE="\u2550"
  STYLE_SIDECOL="\u2551"
  STYLE_TITLEHOLESTART="\u2561"
  STYLE_TITLEHOLEEND="\u255E"
  STYLE_SELECTED="\u25CF"
}

style::thick() {
  STYLE_TOPLEFT="\u250F"
  STYLE_TOPRIGHT="\u2513"
  STYLE_TOPMIDDLE="\u2501"
  STYLE_BOTTOMLEFT="\u2517"
  STYLE_BOTTOMRIGHT="\u251B"
  STYLE_BOTTOMMIDDLE="\u2501"
  STYLE_SIDECOL="\u2503"
  STYLE_TITLEHOLESTART="\u252B"
  STYLE_TITLEHOLEEND="\u2523"
  STYLE_SELECTED="\u25CF"
}

style::thin() {
  STYLE_TOPLEFT="\u250C"
  STYLE_TOPRIGHT="\u2510"
  STYLE_TOPMIDDLE="\u2508"
  STYLE_BOTTOMLEFT="\u2514"
  STYLE_BOTTOMRIGHT="\u2518"
  STYLE_BOTTOMMIDDLE="\u2508"
  STYLE_SIDECOL="\u2502"
  STYLE_TITLEHOLESTART="\u25C0"
  STYLE_TITLEHOLEEND="\u25B6"
  STYLE_SELECTED="\u25C8"
}

style::thinrounded() {
  STYLE_TOPLEFT="\u256D"
  STYLE_TOPRIGHT="\u256E"
  STYLE_TOPMIDDLE="\u2508"
  STYLE_BOTTOMLEFT="\u2570"
  STYLE_BOTTOMRIGHT="\u256F"
  STYLE_BOTTOMMIDDLE="\u2508"
  STYLE_SIDECOL="\u2502"
  STYLE_SELECTED="\u25C9"
}

style::thinroundednosides() {
  STYLE_TOPLEFT="\u256D"
  STYLE_TOPRIGHT="\u256E"
  STYLE_TOPMIDDLE="\u2508"
  STYLE_BOTTOMLEFT="\u2570"
  STYLE_BOTTOMRIGHT="\u256F"
  STYLE_BOTTOMMIDDLE="\u2508"
  STYLE_SELECTED="\u25C9"
}

style::basic() {
  STYLE_TOPLEFT="+"
  STYLE_TOPRIGHT="+"
  STYLE_BOTTOMLEFT="+"
  STYLE_BOTTOMRIGHT="+"
  STYLE_TOPMIDDLE="-"
  STYLE_BOTTOMMIDDLE="-"
  STYLE_SIDECOL="|"
  STYLE_TITLEHOLESTART="="
  STYLE_TITLEHOLEEND="="
  STYLE_SELECTED="*"
}